base_url = "https://blogs.theshastrispace.xyz"
compile_sass = true
generate_feed = true
theme = "hook"
title = "Shastri's Blogs"

taxonomies = [
  {name = "categories"},
  {name = "tags"},
]

[extra]
links = [
    { title = "Home", href = "/" },
    { title = "Categories", href = "/categories" },
    { title = "Tags", href = "/tags" },
]

