base_url = "https://theshasri.xyz"
compile_sass = true
title = "Shastri's blog"
description = "A robust, elegant dark theme"
generate_feed = true
theme = "after-dark"
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[extra]
author = "Naveen "
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]
after_dark_title = "Shastri's Blog"
