base_url = "https://naveenravi07.github.io/blogs/"
compile_sass = true
generate_feeds = true
theme = "hook"
title = "Shastri's Blogs"

taxonomies = [
  {name = "categories"},
  {name = "tags"},
]

[extra]
links = [
    { title = "Home", href = "https://naveenravi07.github.io/blogs/" },
    { title = "Categories", href = "https://naveenravi07.github.io/blogs/categories" },
    { title = "Tags", href = "https://naveenravi07.github.io/blogs/tags" },
]
