base_url = "https://blogs.theshastrispace.xyz/"
compile_sass = true
generate_feed = true
theme = "hook"
title="Shastri's Blogs"

taxonomies = [
  {name = "categories"},
  {name = "tags"},
]

[extra]
links = [
    { title = "Home", href = "https://blogs.theshastrispace.xyz" },
    { title = "Categories", href = "/https://blogs.theshastrispace.xyz/categories" },
    { title = "Tags", href = "https://blogs.theshastrispace.xyz/tags" },
]
