base_url = "https://theshastri.xyz/blogs"
compile_sass = true
generate_feed = true
theme = "hook"
title="Shastri's Blogs"

taxonomies = [
  {name = "categories"},
  {name = "tags"},
]

[extra]
links = [
    { title = "Home", href = "https://theshastri.xyz/blogs" },
    { title = "Categories", href = "https://theshastri.xyz/blogs/categories" },
    { title = "Tags", href = "https://theshastri.xyz/blogs/tags" },
]
